### PR TITLE
Fix for SELECT Table Qualifier

### LINKED ISSUE #780: Select Star with Table Qualifier Does Not Work
A query with `SELECT *` works on one or multiple tables:

```
terrier=# CREATE TABLE xxx (id INT);             
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1),(2),(3),(4);
INSERT 0 4
terrier=# CREATE TABLE yyy (id INT);
CREATE TABLE
terrier=# INSERT INTO yyy VALUES (1),(2),(3),(4);
INSERT 0 4
terrier=# SELECT * FROM xxx JOIN yyy ON xxx.id = yyy.id;
 id | id 
----+----
  1 |  1
  2 |  2
  3 |  3
  4 |  4
(4 rows)
```

But if I add the table name as a qualifier in the output list, it does not work. This query should return the columns from table `xxx` and nothing from table `yyy`:
```
terrier=# SELECT xxx.* FROM xxx JOIN yyy ON xxx.id = yyy.id;
ERROR:  binding failed
```

### PR DESCRIPTION
**Pull request by 17zhangw**
# Fix for SELECT Table Qualifier #780 

## Description

Fix #780.

Historically, `parser::StarExpression` was used for both `COUNT(*)` and `SELECT *`. The PR creates a new `parser::TableStarExpression` used exclusively to handle the cases of `SELECT *` and `SELECT t.*`. During binding, the function `BinderContext::GenerateAllColumnExpressions` is then able to consider the qualified table name (if specified) when generating all column value expressions from a given table.

## Queries that now work
```
CREATE TABLE t (a INT);
SELECT t.* FROM t;
SELECT tt.* FROM t tt;
SELECT t.* FROM t tt; # throws a binder exception
```

### CODE REVIEW

File: src/binder/bind_node_visitor.cpp [hunk 1]
```diff
@@ -79,8 +80,10 @@ void BindNodeVisitor::Visit(common::ManagedPointer<parser::CopyStatement> node)
     node->GetCopyTable()->Accept(common::ManagedPointer(this).CastManagedPointerTo<SqlNodeVisitor>());
 
     // If the table is given, we're either writing or reading all columns
+    auto table_star = parser::TableStarExpression();
```
Comment (lmwnshn) [inline src/binder/bind_node_visitor.cpp:83]: `parser::TableStarExpression table_star`?

**Review by lmwnshn — APPROVED** [review]
Minor change, otherwise LGTM. Let's get @apavlo to weigh in though.
