### PR TITLE
DISTINCT aggregation fix

### LINKED ISSUE #1048: [TPL2] COUNT(DISTINCT()) no longer working.
Amadou had code that would codegen aggregation hash tables [here](https://github.com/cmu-db/terrier/blob/0043d0161e1b08ae77e2e3ec4344d9f1548f1074/src/include/execution/compiler/operator/aggregate_util.h). Unfortunately, this isn't directly drop-in into TPL2 as codegen interfaces have changed and we do some stuff in parallel now.

I talked to @pmenon today and he advised that implementing parallel distincts can be involved, and that he'd recommend forcing serial aggregations if any aggregates are distinct. That assumption should make bringing over the code easier, but it might still take a fair bit of time.

### PR DESCRIPTION
**Pull request by githubxxcc**
#1048
### Problem 
For aggregation with distinct, e.g. `SELECT COUNT(DISTINCT x)` or `SELECT SUM(DISTINCT x) FROM y GROUP BY c`, there is currently no mechanism put in place in the `HashAggregationTranslaor` and `StaticAggregationTranslator` to prevent the same `x` to be advanced to aggregation more than once. 

### Solution 
The high level idea is to have a hash table so that for each tuple value being aggregated, if it needs to be distinct, it should not be advanced to aggregation if it already exists in the hash table. 

Also, the build pipeline for both the `StaticAggregationTranslator` and  `HashAggregationTranslator` would need to be serial since I don't think the hashtable is thread safe.

### CODE REVIEW

**Comment by githubxxcc** [comment]
@kjobanputra @lmwnshn

**Comment by apavlo** [comment]
@githubxxcc You are going to want to add SQL tests. Ask @dniu16 how to do this.

File: src/execution/compiler/operator/hash_aggregation_translator.cpp [hunk 1]
```diff
@@ -29,6 +29,19 @@ HashAggregationTranslator::HashAggregationTranslator(const planner::AggregatePla
   TERRIER_ASSERT(plan.GetAggregateStrategyType() == planner::AggregateStrategyType::HASH,
                  "Expected hash-based aggregation plan node");
   TERRIER_ASSERT(plan.GetChildrenSize() == 1, "Hash aggregations should only have one child");
+  // TODO(kunal&ricky):
+  // We need to modify many of the setup/initialize/teardown logic to add the additional agg_distinct_ht.
+  // A agg_distinct_ht will be a global mapping [distinct aggregate value -> dummy payload],
+  // for each aggregate term that has a distinct predicate.
+  // The agg_distinc_ht should have the same setup/teardown logic like the current global_agg_ht_. But we need to
+  // keep track of multiple hash tables, or we need to have a complex key (aggregate_term_id, tuple_val) to
```
Comment (lmwnshn) [inline src/execution/compiler/operator/hash_aggregation_translator.cpp:37]: Yes, you will need to keep track of multiple hash tables. That is what Amadou's code does.

File: src/execution/compiler/operator/hash_aggregation_translator.cpp [hunk 2]
```diff
@@ -29,6 +29,19 @@ HashAggregationTranslator::HashAggregationTranslator(const planner::AggregatePla
   TERRIER_ASSERT(plan.GetAggregateStrategyType() == planner::AggregateStrategyType::HASH,
                  "Expected hash-based aggregation plan node");
   TERRIER_ASSERT(plan.GetChildrenSize() == 1, "Hash aggregations should only have one child");
+  // TODO(kunal&ricky):
```
Comment (kjobanputra) [inline src/execution/compiler/operator/hash_aggregation_translator.cpp:32]: Since _sum_ and _count_ are both static aggregations, using a hash table in `static_aggregation_translator.cpp` seems sufficient to me for using distinct with either of these aggregations. I don't think editing `hash_aggregation_translator.cpp` is necessary. Thoughts?

File: src/execution/compiler/operator/hash_aggregation_translator.cpp (hunk 1 above)
Comment (githubxxcc) [reply src/execution/compiler/operator/hash_aggregation_translator.cpp:37]: If we have some sort of id to distinguish different aggregate terms, do we still need to keep track of multiple hash tables?

File: src/execution/compiler/operator/hash_aggregation_translator.cpp (hunk 2 above)
Comment (githubxxcc) [reply src/execution/compiler/operator/hash_aggregation_translator.cpp:32]: I think for the `hash_aggregation_translator`, it is now handling cases with presence of Group By clauses. Consider a query like `SELECT COUNT(DISTINCT x), y FROM aaa GROUP BY y`, it will also need to do the distinct aggregate rather than the normal aggregate.

**Comment by githubxxcc** [comment]
The commit 8fa7b7a62245178f55b2c7c053f9eb30769e61a0 should fix the `COUNT(DISTINCT x)` bug. 

### Testing 
However, only command manual line testing was done.  After talking to Jeff, it seems that the sql test is currently unable to specify expected value but only expected number of outputs, which makes it less relevant for catching DISTINCT bug. But still, I can add in some .sql tests after I figure out how to do that with the help of @dniu16 
**Please point to me if there is any other testing in place where I should be adding the tests**

Current manual testing done: 
```
# Setup Queries: 
DROP TABLE IF EXISTS accounts;
CREATE TABLE accounts (user_id INT PRIMARY KEY, email INT NOT NULL, phone INT NOT NULL);
INSERT INTO accounts (user_id, email, phone) VALUES (0, 99, 10);
INSERT INTO accounts (user_id, email, phone) VALUES (1, 99, 10);
INSERT INTO accounts (user_id, email, phone) VALUES (2, 101, 9);

# Test Queries: 
terrier=# SELECT COUNT(DISTINCT email), COUNT(email) FROM accounts;
 ?column? | ?column?
----------+----------
        2 |        3
(1 row)


terrier=# SELECT COUNT(DISTINCT email), COUNT(email), COUNT(DISTINCT phone) FROM accounts;
 ?column? | ?column? | ?column?
----------+----------+----------
        2 |        3 |        2
(1 row)
```

File: src/execution/compiler/operator/hash_aggregation_translator.cpp (hunk 1 above)
Comment (githubxxcc) [reply src/execution/compiler/operator/hash_aggregation_translator.cpp:37]: I think you are right. I need to keep track of multiple hash tables, each for one aggregate, since different aggregates might have different return types.

**Comment by lmwnshn** [comment]
Ping me on slack once you're happy with the tests + it works with strings, thanks! Nice work.

**Comment by githubxxcc** [comment]
Current testing for sanity check passed. Feel free to pull the PR to test it

```
# Set up query 
DROP TABLE accounts;
CREATE TABLE accounts (user_id INT PRIMARY KEY, email VARCHAR(256), phone INT NOT NULL, years float NOT NULL);
INSERT INTO accounts VALUES (0, 'user1@gamil.com',10, 10.5);
INSERT INTO accounts VALUES (1, 'user1@gamil.com',10, 0.5);
INSERT INTO accounts VALUES (2, 'user1@gamil.com',10,  0.5);
INSERT INTO accounts VALUES (3, 'user2@gamil.com',100, 1.0);

--------------------
SELECT 
    COUNT(DISTINCT email) as dist_str_cnt, 
    COUNT(email) as str_cnt,
    MIN(email) as str_min,
    MAX(email) as str_max
FROM accounts;

terrier-# 
 dist_str_cnt | str_cnt |     str_min     |     str_max
--------------+---------+-----------------+-----------------
            2 |       4 | user1@gamil.com | user2@gamil.com


--------------------
SELECT 
    COUNT(DISTINCT phone) as dist_int_cnt,
    COUNT(phone) as int_cnt,
    AVG(DISTINCT phone) as dist_int_avg,
    AVG(phone) as int_avg,
    MAX(DISTINCT phone) as dist_int_max,
    MAX(phone) as int_max,
    MIN(DISTINCT phone) as dist_int_min,
    MIN(phone) as int_min
FROM accounts;

terrier-# 
 dist_int_cnt | int_cnt | dist_int_avg |  int_avg  | dist_int_max | int_max | dist_int_min | int_min
--------------+---------+--------------+-----------+--------------+---------+--------------+---------
            2 |       4 |    55.000000 | 32.500000 |          100 |     100 |           10 |      10
# 

--------------------
SELECT 
    COUNT(DISTINCT years) as dist_float_cnt,
    COUNT(years) as float_cnt,
    AVG(DISTINCT years) as dist_float_avg,
    AVG(years) as float_avg,
    MIN(years) as float_min,
    MAX(years) as float_max
FROM accounts;

terrier-#:
 dist_float_cnt | float_cnt | dist_float_avg | float_avg | float_min | float_max
----------------+-----------+----------------+-----------+-----------+-----------
              3 |         4 |       4.000000 |  3.125000 |  0.500000 | 10.500000
(1 row)

--------------------
SELECT 
    COUNT(DISTINCT email) as dist_str_cnt, 
    COUNT(email) as str_cnt,
    MIN(email) as str_min,
    MAX(email) as str_max
FROM accounts GROUP BY phone;
terrier-# 
 dist_str_cnt | str_cnt |     str_min     |     str_max
--------------+---------+-----------------+-----------------
            1 |       1 | user2@gamil.com | user2@gamil.com
            1 |       3 | user1@gamil.com | user1@gamil.com
(2 rows)

SELECT 
    COUNT(DISTINCT years) as dist_float_cnt,
    COUNT(years) as float_cnt,
    AVG(DISTINCT years) as dist_float_avg,
    AVG(years) as float_avg,
    MIN(years) as float_min,
    MAX(years) as float_max
FROM accounts GROUP BY email;
 
dist_float_cnt | float_cnt | dist_float_avg | float_avg | float_min | float_max
----------------+-----------+----------------+-----------+-----------+-----------
              2 |         3 |       5.500000 |  3.833333 |  0.500000 | 10.500000
              1 |         1 |       1.000000 |  1.000000 |  1.000000 |  1.000000
(2 rows)

SELECT 
    COUNT(DISTINCT phone) as dist_int_cnt,
    COUNT(phone) as int_cnt,
    AVG(DISTINCT phone) as dist_int_avg,
    AVG(phone) as int_avg,
    MAX(DISTINCT phone) as dist_int_max,
    MAX(phone) as int_max,
    MIN(DISTINCT phone) as dist_int_min,
    MIN(phone) as int_min
FROM accounts GROUP BY years;

 dist_int_cnt | int_cnt | dist_int_avg |  int_avg   | dist_int_max | int_max | dist_int_min | int_min
--------------+---------+--------------+------------+--------------+---------+--------------+---------
            1 |       2 |    10.000000 |  10.000000 |           10 |      10 |           10 |      10
            1 |       1 |   100.000000 | 100.000000 |          100 |     100 |          100 |     100
            1 |       1 |    10.000000 |  10.000000 |           10 |      10 |           10 |      10
(3 rows)
```

**Comment by githubxxcc** [comment]
@kjobanputra Feel free to help generate a more comprehensive and robust SQL traces files based on the example I used. 
It will be good to test on a larger dataset if possible so that we trigger the hash collision and the partition overflow (for `hash_aggregation_translator`

File: src/execution/compiler/operator/hash_aggregation_translator.cpp [hunk 3]
```diff
@@ -29,6 +29,21 @@ HashAggregationTranslator::HashAggregationTranslator(const planner::AggregatePla
...
+    compilation_context->Prepare(*agg_term->GetChild(0));
+    if (agg_term->IsDistinct()) {
+      distinct_filters_.emplace(
+          std::make_pair(agg_term_idx, DistinctAggregationFilter(agg_term_idx, agg_term, plan.GetGroupByTerms().size(),
+                                                                 compilation_context, pipeline, GetCodeGen())));
+    }
+  }
+
+  if (!distinct_filters_.empty()) {
+    build_pipeline_.UpdateParallelism(Pipeline::Parallelism::Serial);
```
Comment (lmwnshn) [inline src/execution/compiler/operator/hash_aggregation_translator.cpp:44]: Add a TODO comment here saying that the presence of distinct forces serial aggregations.

File: src/execution/compiler/operator/hash_aggregation_translator.cpp [hunk 4]
```diff
@@ -29,6 +29,21 @@ HashAggregationTranslator::HashAggregationTranslator(const planner::AggregatePla
   TERRIER_ASSERT(plan.GetAggregateStrategyType() == planner::AggregateStrategyType::HASH,
                  "Expected hash-based aggregation plan node");
   TERRIER_ASSERT(plan.GetChildrenSize() == 1, "Hash aggregations should only have one child");
+
+  for (size_t agg_term_idx = 0; agg_term_idx < plan.GetAggregateTerms().size(); agg_term_idx++) {
```
Comment (lmwnshn) [inline src/execution/compiler/operator/hash_aggregation_translator.cpp:33]: Style/consistency nit: Is there a reason this was moved from below the GetGroupByTerms?

File: src/execution/compiler/pipeline.cpp [hunk 5]
```diff
@@ -31,6 +31,7 @@ Pipeline::Pipeline(CompilationContext *ctx)
              [this](CodeGen *codegen) { return codegen_->MakeExpr(state_var_); }) {}
 
 Pipeline::Pipeline(OperatorTranslator *op, Pipeline::Parallelism parallelism) : Pipeline(op->GetCompilationContext()) {
+  UpdateParallelism(parallelism);
```
Comment (lmwnshn) [inline src/execution/compiler/pipeline.cpp:34]: Nice catch! I think this fixes an actual bug (in parallelism computation).

File: src/include/execution/compiler/operator/distinct_aggregation_util.h [hunk 6]
```diff
@@ -0,0 +1,192 @@
+#pragma once
+#include <execution/compiler/if.h>
```
Comment (lmwnshn) [inline src/include/execution/compiler/operator/distinct_aggregation_util.h:2]: Nit: include with `""` not `<>` for our own files.

File: src/include/execution/sql/aggregators.h [hunk 7]
```diff
@@ -171,8 +171,13 @@ class MaxAggregate {
     if (val.is_null_) {
       return;
     }
+
+    if (max_.is_null_) {  // Initial null value should not be larger than any string
```
Comment (lmwnshn) [inline src/include/execution/sql/aggregators.h:175]: This is generic max, comment shouldn't be specifically talking about strings.

File: src/include/execution/sql/aggregators.h [hunk 8]
```diff
@@ -182,8 +187,13 @@ class MaxAggregate {
     if (that.max_.is_null_) {
       return;
     }
+
+    if (max_.is_null_) {  // Initial null value should not be larger than any string
```
Comment (lmwnshn) [inline src/include/execution/sql/aggregators.h:191]: This is generic max, comment shouldn't be specifically talking about strings.

File: src/include/execution/sql/aggregators.h [hunk 9]
```diff
@@ -241,8 +251,13 @@ class MinAggregate {
     if (val.is_null_) {
       return;
     }
+
+    if (min_.is_null_) {  // Initial null String should not be smaller than any string
```
Comment (lmwnshn) [inline src/include/execution/sql/aggregators.h:255]: This is generic max, comment shouldn't be specifically talking about strings.

File: src/include/execution/sql/aggregators.h [hunk 10]
```diff
@@ -252,8 +267,13 @@ class MinAggregate {
     if (that.min_.is_null_) {
       return;
     }
+
+    if (min_.is_null_) {  // Initial null String should not be smaller than any string
```
Comment (lmwnshn) [inline src/include/execution/sql/aggregators.h:271]: This is generic max, comment shouldn't be specifically talking about strings.

File: src/include/execution/compiler/operator/distinct_aggregation_util.h [hunk 11]
```diff
@@ -0,0 +1,192 @@
...
+
+#include <vector>
+
+#include "execution/compiler/compilation_context.h"
+#include "execution/compiler/state_descriptor.h"
+#include "execution/compiler/work_context.h"
+#include "planner/plannodes/aggregate_plan_node.h"
```
Comment (lmwnshn) [inline src/include/execution/compiler/operator/distinct_aggregation_util.h:9]: Nit: Please forward declare to improve compilation time.

File: src/include/execution/compiler/operator/distinct_aggregation_util.h [hunk 12]
```diff
@@ -0,0 +1,192 @@
...
+                         const std::vector<ast::Expr *> &group_bys) const;
+
+ private:
+  /**
+   * Get the value to be aggregated from the KeyType payload
+   * @param codegen CodeGen
+   * @param row KeyType struct
+   * @return the aggregate value
+   */
+  ast::Expr *GetAggregateValue(CodeGen *codegen, ast::Expr *row) const {
```
Comment (lmwnshn) [inline src/include/execution/compiler/operator/distinct_aggregation_util.h:93]: Nit: please move function definitions to .cpp file for compilation time.

**Review by lmwnshn — CHANGES_REQUESTED** [review]
Nice!

1. Waiting for tests, in the meantime, some quick nitpicky things regarding TPL style and compilation time. In particular, including plan nodes in header files is usually very painful for compilation.
2. Count(Distinct()) on booleans don't work (they do in postgres).

I'll take a second pass after tests are in.

**Comment by kjobanputra** [comment]
I added the distinct aggregations in a separate file so it's easier for the reviewer to look at it. I can merge this with Jeff's aggregation trace file after it's approved.

**Comment by githubxxcc** [comment]
I ran the trace file manually and compared the results, I think the formatting issue for decimals/floats mentioned here https://github.com/cmu-db/terrier/pull/1144#issuecomment-686614760 is making the hashes not matched. 

For example, one of the failed trace: 
```
terrier=# SELECT SUM(DISTINCT gpa) as distinctGpaSum, SUM(gpa) as gpaSum, SUM(DISTINCT age) as distinctAgeSum from studentTable;
 distinctgpasum |   gpasum   | distinctagesum
----------------+------------+----------------
      14.500000 | 365.000002 |             95
(1 row)


<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

postgres=# SELECT SUM(DISTINCT gpa) as distinctGpaSum, SUM(gpa) as gpaSum, SUM(DISTINCT age) as distinctAgeSum from studentTable;
 distinctgpasum |      gpasum       | distinctagesum
----------------+-------------------+----------------
           14.5 | 364.9999999999993 |             95
(1 row)


```

I remember it being brought up in the meeting, but couldn't not recall if we have reach a solution to this? 

@dniu16 @apavlo

File: src/execution/compiler/operator/hash_aggregation_translator.cpp (hunk 4 above)
Comment (githubxxcc) [reply src/execution/compiler/operator/hash_aggregation_translator.cpp:33]: This was so that `distinct_filters_` could be initialized, and we could then update the parallelism of `build_pipeline_`.

**Review by lmwnshn — APPROVED** [review]
LGTM if tests pass.
