### PR TITLE
Prevent optimizer from issuing plans with range scans on hashmap indexes

### LINKED ISSUE #1132: Optimizer Incorrectly Selects Hash Index For Range Scans
If you try to perform a range scan on a catalog table's primary key, the system crashes because we use hash indexes.

**Client:**
```
terrier=# SELECT * FROM pg_catalog.pg_class WHERE reloid > 1;
```

**Server:**
```
terrier: /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/storage/index/index.h:128: 
virtual void terrier::storage::index::Index::ScanAscending(const terrier::transaction::TransactionContext&, terrier::storage::index::ScanType, uint32_t, terrier::storage::ProjectedRow*, terrier::storage::ProjectedRow*, uint32_t, std::vector<terrier::storage::TupleSlot>*): 
Assertion `(false) && ("You called a method on an index type that hasn't implemented it.")' failed.
```

I think that this is likely the reason why #748 was failing before. We now crash instead of returning nothing.

We need to fix the optimizer to recognize the DBMS cannot perform a range scan on a hash index and fallback to using a seq scan for this query. To do this, we should add additional meta-data (in catalog?) that specifies whether an index supports range scans. Then the optimizer's transformation rule will check whether the expression on the keys is not an equality comparison and then skip any hash indexes.

**Stack Trace**
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff52308b1 in __GI_abort () at abort.c:79
#2  0x00007ffff522042a in __assert_fail_base (fmt=0x7ffff53a7a38 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
assertion=assertion@entry=0x55555925c500 "(false) && (\"You called a method on an index type that hasn't implemented it.\")", 
file=file@entry=0x55555925c480 "/home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/storage/index/index.h", line=line@entry=128, 
function=function@entry=0x55555926c620 <terrier::storage::index::Index::ScanAscending(terrier::transaction::TransactionContext const&, terrier::storage::index::ScanType, unsigned int, terrier::storage::ProjectedRow*, terrier::storage::ProjectedRow*, unsigned int, std::vector<terrier::storage::TupleSlot, std::allocator<terrier::storage::TupleSlot> >*)::__PRETTY_FUNCTION__> "virtual void terrier::storage::index::Index::ScanAscending(const terrier::transaction::TransactionContext&, terrier::storage::index::ScanType, uint32_t, terrier::storage::ProjectedRow*, terrier::stora"...) at assert.c:92
#3  0x00007ffff52204a2 in __GI___assert_fail (assertion=0x55555925c500 "(false) && (\"You called a method on an index type that hasn't implemented it.\")", 
file=0x55555925c480 "/home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/storage/index/index.h", line=128, 
function=0x55555926c620 <terrier::storage::index::Index::ScanAscending(terrier::transaction::TransactionContext const&, terrier::storage::index::ScanType, unsigned int, terrier::storage::ProjectedRow*, terrier::storage::ProjectedRow*, unsigned int, std::vector<terrier::storage::TupleSlot, std::allocator<terrier::storage::TupleSlot> >*)::__PRETTY_FUNCTION__> "virtual void terrier::storage::index::Index::ScanAscending(const terrier::transaction::TransactionContext&, terrier::storage::index::ScanType, uint32_t, terrier::storage::ProjectedRow*, terrier::stora"...) at assert.c:101
#4  0x000055555730c31e in terrier::storage::index::Index::ScanAscending (this=0x613000000ac0, txn=..., scan_type=terrier::storage::index::ScanType::OpenHigh, num_attrs=1, low_key=0x6030001ffed0, high_key=0x6030001fff00, 
limit=0, value_list=0x7fff6dca3058) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/storage/index/index.h:128
#5  0x000055555786c82b in terrier::execution::sql::IndexIterator::ScanAscending (this=0x7fff6dca2fe8, scan_type=terrier::storage::index::ScanType::OpenHigh, limit=0)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/execution/sql/index_iterator.cpp:45
#6  0x0000555556c343d4 in OpIndexIteratorScanAscending (iter=0x7fff6dca2fe8, scan_type=terrier::storage::index::ScanType::OpenHigh, limit=0)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/execution/vm/bytecode_handlers.h:1609
#7  0x0000555556c08706 in terrier::execution::vm::VM::Interpret (this=0x7fff6dca69a0, ip=0x619000032c02 "\360\001", frame=0x7fff6dca3240) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/execution/vm/vm.cpp:1699
#8  0x0000555556c10815 in terrier::execution::vm::VM::ExecuteCall (this=0x7fff6dca69a0, ip=0x619000032e02 "\250", caller=0x7fff6dca69e0) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/execution/vm/vm.cpp:2341
#9  0x0000555556bf6e10 in terrier::execution::vm::VM::Interpret (this=0x7fff6dca69a0, ip=0x619000032df6 "\003", frame=0x7fff6dca69e0) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/execution/vm/vm.cpp:447
#10 0x0000555556beb7ab in terrier::execution::vm::VM::InvokeFunction (module=0x60400002c5d0, func_id=5, args=0x7fff6dca6a90 "\220\365\a") at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/execution/vm/vm.cpp:112
#11 0x000055555674412e in bool terrier::execution::vm::Module::GetFunction<void, void*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, terrier::execution::vm::ExecutionMode, std::function<void (void*)>*)::{lambda(void*)#1}::operator()(void*) const (__closure=0x7fff6dca6d90, args#0=0x60200007f590) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/execution/vm/module.h:222
#12 0x000055555674a34a in std::_Function_handler<void (void*), bool terrier::execution::vm::Module::GetFunction<void, void*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, terrier::execution::vm::ExecutionMode, std::function<void (void*)>*)::{lambda(void*)#1}>::_M_invoke(std::_Any_data const&, void*&&) (__functor=..., __args#0=@0x7fff6dca6b30: 0x60200007f590)
at /usr/include/c++/7/bits/std_function.h:316
#13 0x0000555556744569 in std::function<void (void*)>::operator()(void*) const (this=0x7fff6dca6d90, __args#0=0x60200007f590) at /usr/include/c++/7/bits/std_function.h:706
#14 0x000055555673f6ab in terrier::execution::compiler::ExecutableQuery::Fragment::Run (this=0x60600001bb00, query_state=0x60200007f590, mode=terrier::execution::vm::ExecutionMode::Interpret)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/execution/compiler/executable_query.cpp:43
#15 0x0000555556741ebe in terrier::execution::compiler::ExecutableQuery::Run (this=0x60d000017530, exec_ctx=..., mode=terrier::execution::vm::ExecutionMode::Interpret)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/execution/compiler/executable_query.cpp:160
#16 0x00005555565a450b in terrier::trafficcop::TrafficCop::RunExecutableQuery (this=0x606000012380, connection_ctx=..., out=..., portal=...)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/traffic_cop/traffic_cop.cpp:392
#17 0x000055555617f2e3 in terrier::network::ExecutePortal (connection_ctx=..., portal=..., out=..., t_cop=..., explicit_txn_block=false)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/network/postgres/postgres_network_commands.cpp:39
#18 0x00005555561811bf in terrier::network::SimpleQueryCommand::Exec (this=0x604000028310, interpreter=..., out=..., t_cop=..., connection=...)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/network/postgres/postgres_network_commands.cpp:175
#19 0x00005555561f2203 in terrier::network::PostgresProtocolInterpreter::Process (this=0x611000039fc0, in=..., out=..., t_cop=..., context=...)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/network/postgres/postgres_protocol_interpreter.cpp:45
#20 0x0000555557bbbdf4 in terrier::network::ConnectionHandle::Process (this=0x61300001ff50) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/network/connection_handle.h:121
#21 0x0000555557bb7d06 in terrier::network::ConnectionHandle::StateMachine::<lambda(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>)>::operator()(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>) const (__closure=0x0, w=...) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/network/connection_handle.cpp:105
#22 0x0000555557bb7d25 in terrier::network::ConnectionHandle::StateMachine::<lambda(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>)>::_FUN(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>) () at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/network/connection_handle.cpp:105
#23 0x0000555557bb9b5c in terrier::network::ConnectionHandle::StateMachine::Accept (this=0x61300001ff70, action=terrier::network::Transition::WAKEUP, connection=...)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/network/connection_handle.cpp:155
#24 0x0000555556c82683 in terrier::network::ConnectionHandle::HandleEvent (this=0x61300001ff50, fd=124, flags=2) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/network/connection_handle.h:96
#25 0x0000555557bbbe84 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const (__closure=0x0, fd=124, flags=2, arg=0x61300001ff50)
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/network/connection_handle.h:152
#26 0x0000555557bbbeb3 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) ()
at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/network/connection_handle.h:152
#27 0x00007ffff69c88f8 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#28 0x00007ffff69c933f in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#29 0x0000555556c6ae0a in terrier::EventUtil::EventBaseDispatch (base=0x617000010000) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/common/event_util.h:92
#30 0x0000555556c6aea5 in terrier::common::NotifiableTask::EventLoop (this=0x610000008040) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/common/notifiable_task.h:159
#31 0x0000555556c8219c in terrier::common::NotifiableTask::RunTask (this=0x610000008040) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/common/notifiable_task.h:166
#32 0x0000555556c6b2fa in terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}::operator()() const (
__closure=0x60300004a9e8) at /home/wanshenl/aint/nutin/to/fuck/wit/terrier/src/include/common/dedicated_thread_registry.h:83
#33 0x0000555556c6cae7 in std::__invoke_impl<void, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(std::__invoke_other, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) (__f=...)
at /usr/include/c++/7/bits/invoke.h:60
#34 0x0000555556c6bf98 in std::__invoke<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#35 0x0000555556c6df52 in std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x60300004a9e8) at /usr/include/c++/7/thread:234
#36 0x0000555556c6df23 in std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::operator()() (this=0x60300004a9e8) at /usr/include/c++/7/thread:243
#37 0x0000555556c6df02 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> > >::_M_run() (this=0x60300004a9e0) at /usr/include/c++/7/thread:186
#38 0x00007ffff5c546df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#39 0x00007ffff6c026db in start_thread (arg=0x7fff6dca9700) at pthread_create.c:463
#40 0x00007ffff5311a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### PR DESCRIPTION
**Pull request by jrolli**
# Heading

Fixes #1132 

## Description

The optimizer was implicitly assuming that all indexes supported all modes of querying.  Therefore, it would create plans that called for range scans on hashmap indexes and cause the system to crash at runtime.  This PR inserts a check inside `IndexUtil::CheckPredicates` that ensures we force a negative response if the predicate would require this situation.

## Further work

Ideally, this should be a more general check which allows adding additional index types like PostgreSQL does.  However, that would require implementing several more catalog tables and logic to have the optimizer query that information when checking predicates.

### CODE REVIEW

File: test/catalog/catalog_sql_test.cpp [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+
+#include "common/settings.h"
+#include "gtest/gtest.h"
+#include "main/db_main.h"
+#include "test_util/test_harness.h"
+
+namespace noisepage::catalog {
+
+// These are end-to-end tests of the catalog which cannot be performed with the
+// JUnit trace framework because we expect divergent behavior from PostgreSQL
```
Comment (xinzhu-cai) [inline test/catalog/catalog_sql_test.cpp:16]: AFAK, the trace framework is comparing the hash value of the execution results. I don't understand how divergent behavior from PostgresSQL prevents us from using the JUnit trace framework. Could you explain it?

Comment (jrolli) [reply test/catalog/catalog_sql_test.cpp:16]: The JUnit framework generates the hashes and result sets in the traces from a run against PostgreSQL which we are storing and then using as a reference point for what Noisepage should be outputting.  We could hand-craft a trace file, but I think that is fragile in the long run and not substantially different from what we are doing here.

**Review by xinzhu-cai — APPROVED** [review]
LGTM
